export const categories = [
  "All essentials",
  "Premium Beverages",
  "Mixers",
  "Glassware",
  "Snacks",
  "Pantry",
];
export const products = [
  {
    id: "orange",
    name: "Orange fruit juice",
    brand: "DRINKS",
    category: "Premium Beverages",
    size: "1 bottle",
    price: 95,
    oldPrice: 110,
    image: "/products/orange.webp",
  },
  {
    id: "tonic",
    name: "Soda & soft drinks",
    brand: "REFRESHMENTS",
    category: "Mixers",
    size: "1 bottle",
    price: 65,
    image: "/products/tonic.webp",
  },
  {
    id: "chips",
    name: "Fresh red apples",
    brand: "FRESH PICKS",
    category: "Snacks",
    size: "500 g",
    price: 55,
    oldPrice: 65,
    image: "/products/chips.webp",
  },
  {
    id: "glasses",
    name: "Everyday drinking glass",
    brand: "TABLE & HOME",
    category: "Glassware",
    size: "1 piece",
    price: 349,
    image: "/products/glasses.webp",
  },
  {
    id: "coffee",
    name: "Nescafé instant coffee",
    brand: "NESCAFÉ",
    category: "Premium Beverages",
    size: "1 jar",
    price: 125,
    image: "/products/coffee.webp",
  },
  {
    id: "nuts",
    name: "Fresh strawberries",
    brand: "FRESH PICKS",
    category: "Snacks",
    size: "250 g",
    price: 199,
    oldPrice: 225,
    image: "/products/nuts.webp",
  },
  {
    id: "soda",
    name: "Bottled mineral water",
    brand: "EVERYDAY DRINKS",
    category: "Mixers",
    size: "1 bottle",
    price: 40,
    image: "/products/soda.webp",
  },
  {
    id: "oats",
    name: "Long grain rice",
    brand: "PANTRY ESSENTIALS",
    category: "Pantry",
    size: "1 kg",
    price: 145,
    image: "/products/oats.webp",
  },
].map((p) => ({
  ...p,
  stock: 24,
  active: true,
  type: "bag",
  color: "#ddd",
  label: "",
}));
export const money = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value);
